networks:
  reverse-proxy: { external: true }

services:
  waves-server:
    build:
      context: .
      dockerfile: dockerfiles/webserver.Dockerfile
    volumes:
      - ./static/recordings:/app/static/recordings:ro
    restart: unless-stopped
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mixes.rule=Host(`mixes.lucascott.com`)"
      - "traefik.http.routers.mixes.entrypoints=websecure"
      - "traefik.http.routers.mixes.tls=true"
      - "traefik.http.routers.mixes.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.mixes.tls.domains[0].sans=*.lucascott.com"

  audiowaveform:
    build:
      dockerfile: dockerfiles/audiowaveform.Dockerfile
    volumes:
      - ./static/recordings:/monitor
